### ISSUE TITLE
GPU translation currently broken?

### ISSUE THREAD

**Issue by bhaddow** [amunmt/amunmt#27]
It outputs 3 lines then exits, no error message. Script found in /home/bhaddow/experiments/wmt17/backtrans/bench/translate-gpu.sh

Configuration (tried changing thread and batch settings)
# Paths are relative to config file location
relative-paths: yes

# performance settings
beam-size: 5
normalize: yes
gpu-threads: 4
cpu-threads: 2
#mini-batch: 60
#maxi-batch: 1200

# scorer configuration
scorers:
  F0:
    path: model.npz
    type: Nematus

# scorer weights
weights:
  F0: 1.0

# vocabularies
source-vocab: vocab.en.json
target-vocab: vocab.cs.json

**Comment by emjotde** [comment]
Confirmed. Guys, we need regression tests. I am close to banning all commits to master for a while and reverting back to code before the batch decoding. It's good to have people trying current code, but we are breaking basic functions too often.

**Comment by emjotde** [comment]
@bhaddow revision 63c70c91b29b35220c2f89d648658a8ab5103cb3 seems to be fine for GPU decoding. The new batch-decoding works for instance with parameters:

```
--beam-size 5 --mini-batch 100 --maxi-batch 1000
```

Which will preload 10 mini-batches and process them by length.

**Comment by hieuhoang** [comment]
Agreed. Can base the regression on pre-batch results

Hieu
Sent while bumping into things

**Comment by emjotde** [comment]
Branch `dev` for all new stuff. I would freeze `master` for a while after we fixed this issue.

**Comment by emjotde** [comment]
@bhaddow Weird, recompilation seems to help?

**Comment by bhaddow** [comment]
I deleted CMakeFiles CMakeCache.txt cmake_install.cmake and bin from my build directory, reran cmake and make, but I still have the problem.

However I confirm that 63c70c9 is fine.

**Comment by emjotde** [comment]
Your yaml file is also a bit weird. Set cpu-threads to 0, just keep the gpu-threads at 1 or more. I am thinking of reverting master to 63c70c9 for now. The current version is in branch `dev`.

**Comment by hieuhoang** [comment]
can you not revert yet. Let me retest it, pretty sure GPU translation is working, I check it for speed and accuracy every time I check in

**Comment by emjotde** [comment]
I think the problem is the use of cpu-threads and gpu-threads together. That seems to break stuff for me.

**Comment by hieuhoang** [comment]
that's unlikely to work with batching so the problem won't go away by reverting. 

The issue is how we support different devices that supports different batching (eg GPUs with different RAM and cores, CPU).

**Comment by emjotde** [comment]
It even breaks with mini-batch 1 and maxi-batch 1. Maybe we should disable it? Either use CPU or GPU?

**Comment by hieuhoang** [comment]
lemme check

**Comment by bhaddow** [comment]
So why have the two options if they don't work together? Just --threads was fine.

**Comment by bhaddow** [comment]
And how do you get a minibatch of 100 to work? On a 1080, it works with 10, but crashes (memory) with 20. This is with 1 gpu thread and no cpu threads.

**Comment by emjotde** [comment]
They used to work before we had batching. I am still thinking they should work, it would just require more complex scheduling. However, I am not sure using them together actually makes sense, when the GPU is 50x faster than the CPU. You are more likely to introduce slow-downs than speed-ups. 

Having them was meant to be able to use a pure CPU version or GPU version with the same binary. You can do --cpu-threads 16 and --gpu-threads 0, this will only use the CPU. Then you can have --cpu-threads 0 and --gpu-threads 3 which uses only gpu and can result in minor speed-ups for gpu compared to single thread.

**Comment by hieuhoang** [comment]
They should work together. Eventually, we prob have to bite the bullet and have things like batch size & threads to be device-specific params

**Comment by bhaddow** [comment]
I understand now. It wasn't clear to me why the threads parameter got split into two, and I thought boosting both might help. imho it would be clearer if --device was used to specify the device and --threads to specify the number of threads - unless there really is a use-case for multiple cpu and gpu threads.

**Comment by emjotde** [comment]
Maybe we should switch to string devices? --device gpu0,gpu1,gpu2,gpu3 or --device cpu, then --threads would be threads per device. Forbidding mixing gpu0,cpu.

**Comment by kpu** [comment]
GNU parallel `--sshlogin` style?  
gpu0/4,gpu1/3

**Comment by emjotde** [comment]
Do we need to be able to specify threads in such a fine-grained way? --device gpu0,gpu1 --threads 3 would mean 6 actual threads. Confusing?

For the pure CPU version (when compiled without cuda support) we can just do --threads and not display a device option.

**Comment by hieuhoang** [comment]
+1 for @emjotde idea. We can have CPU + GPU of different kinds if we do the following - keep maxi-batch a global param but mini-batch is device-specific. eg

--device GPU0, GPU1, CPU
--threads 1,1,32
--mini-batch 100,20,1

**Comment by bhaddow** [comment]
This is starting to look like a Moses command line that you end up having to write a perl script to generate. Most people don't want to mix CPUs and GPUs, and want the same number of threads and batch size on each GPU. So use @emjotde's original suggestion -- with perhaps an advanced formulation for heterogeneous environments -- if you really want to support them.

**Comment by emjotde** [comment]
@bhaddow has a point. Let's keep it simple.

**Comment by hieuhoang** [comment]
It will have to be implemented eventually when we buy new GPUs to slot into existing PC with old GPUs. Supporting CPUs alongside GPUs is a proxy for the heteroegenous environment.

Having an advanced formulation isn't really an option 'cos we'll then have 2 formats to look after

**Comment by emjotde** [comment]
on zisa:

```
cd /home/marcin/un/en-fr.marian
/home/marcin/amunmt/build/bin/amun -m ../en-fr/model.npz.dev.npz -s train.tok.clean.bpe.en.json -t train.tok.clean.bpe.fr.json -n -b 12 -d 1 --maxi-batch 1 --mini-batch 1 -i dev.tok.bpe.en
```

gives me a segfault with current master. Inside Transpose?

**Comment by hieuhoang** [comment]
Barry's models work ok with 1 gpu, 12 cpu, 1 cpu + 12 gpu. It doesn't work with 2 GPUs, but then that gave no speed benefit anyway 'cos batching is already saturating the cores. but is should still work - i'll debug it later. 

1 GPU is 30 times faster than 12 CPU cores. About 10 sentences differ in 10k sentences

**Comment by emjotde** [comment]
Still, something is very wrong, see segfault above.

**Comment by hieuhoang** [comment]
i'll take a look tmrw

**Comment by emjotde** [comment]
Actually, that might be because someone is hogging all the GPUs on zisa, compeletly filled to the rim.

**Comment by kpu** [comment]
That would be a bug in TensorFlow ;-).  I've killed the job since it was hogging GPUs and not using them.

**Comment by emjotde** [comment]
OK. Now segfault now. Thanks. Lesson: we need better CUDA error reporting :)

**Comment by bhaddow** [comment]
I'm now thinking it was a silent out-of-memory error.
--gpu-threads 4 --mini-batch 100 causes the silent exit
Increasing mini-batch to 1000 gives a bad_alloc.
Doesn't really explain why the issue was fixed when I revert to an earlier version. Unless it was some coincidental collisions with our TensorSlow friend.

**Comment by emjotde** [comment]
reduce gpu-threads to 1, potential speed up with batching is minimal, but it probably multiplies peak memory usage.

**Comment by hieuhoang** [comment]
@emjotde the zisa model works for me on my machine if I change -d 1 -> -d 0

**Comment by emjotde** [comment]
@hieuhoang yes, it was a memory problem. We should add checks on allocation, so it will throw an error not just segfault.

**Comment by hieuhoang** [comment]
agreed. I'll use my little laptop

**Comment by hieuhoang** [comment]
was finking. Adding allocation checks doesn't solve the underlying problem of failure during translation. Ideally, GPU-amun should NEVER have a runtime memory problem during translation otherwise it would be unpredictable in production. We can do this by only allocating memory during init. 

Most of the model data is allocated @ init but there are some significant mem alloc for each batch, especially shared memory and thread-specific memory.

**Comment by emjotde** [comment]
Define significant. Shared memory is usually a couple of bytes per thread, also doesn't that come from an entirely different pool?

What we need at least is stuff like that around cuda invocations: https://github.com/emjotde/Marian/blob/master/src/tensors/tensor_gpu.h#L37

**Comment by hieuhoang** [comment]
You're right. A lot of the share mem alloc varies with batch size, it's more of a couple of KB now rather than B. However, it's not the cause of mem issues when I use barry's model with mini-batch=40

I found the cause for the crash - it's not shared mem but global mem. GPU/matrix::Resize is being called with row=499200, cols=2048, which is 7.6GB. I traced it back to the Alignment::GetAlignedSourceContext() L135 Broadcast(). Basically, the matrix size is dependent on mini-batch and source length.

The only way I can think of is to have an option of a fixed matrix, a max input length. Any input above that is truncated or causes a throw.

**Comment by emjotde** [comment]
Actually I just fixed that in Marian yesterday. We can do it the same way: We can do the broadcast virtually with a simultaneous reduce, that way this huge matrix is never constructed but immediately reduced. For that you need to factor the following vector multiplication into that. We will fix that together with Tomasz.

**Comment by hieuhoang** [comment]
ah ok. Another solution would be variable sized mini-batches. For another time

**Comment by emjotde** [comment]
On the other hand, how does the number 499200 come to be? What's the sentence length, beam size, batch-size factorization of this?

**Comment by hieuhoang** [comment]
err, good question - there's a sentence of length 1040. We should protect ourselves against that

**Comment by emjotde** [comment]
slicing and dicing.

**Comment by hieuhoang** [comment]
mini-batch 1

**Comment by hieuhoang** [comment]
discard

**Comment by bhaddow** [comment]
Please don't discard - that will really screw things up. But yes, I
shouldn't have given it that sentence in the first place.

**Comment by emjotde** [comment]
I would cut it into max-length pieces somehow and translate piece by piece? Messes up bookkeeping a bit.

**Comment by hieuhoang** [comment]
Should we truncate? even to 0 sentence perhaps. It's an obvious garbage input and pointless to try to translate it. fyi, the offending line is

As for the possibility of running against Hillary Clinton , Ru@@ bio was quick to criticize the presump@@ tive Democratic nom@@ inee . \ n \ u@@ 00@@ 22 , &quot; &quot; duration &quot; : 127 , &quot; date &quot; : &quot; 2015 @-@ 01 @-@ 12 18 : 50 : 00 , &quot; &quot; key@@ words &quot; : &quot; Video , News , CBS , Marco Ru@@ bio , , &quot; &quot; image &quot; : { &quot; path &quot; : &quot; http : \ / \ / c@@ b@@ s@@ news@@ 2.@@ c@@ b@@ si@@ stat@@ ic@@ .com \ / hub \ / i \ / r \ / 2015 \ / 01 \ / 13 \ / 7@@ f@@ d@@ 70@@ 6@@ 68 @-@ e@@ eff @-@ 45@@ f@@ 0 @-@ b@@ 4@@ c@@ 3 @-@ 5@@ b@@ 3@@ b@@ 2@@ b@@ 2@@ b@@ 94@@ 57 \ / thumbnail \ / 140@@ x@@ 90 \ / 1@@ e@@ 1@@ d@@ 08@@ 29@@ d@@ c@@ f@@ 5@@ a@@ 65@@ d@@ 26@@ fac@@ 6@@ da@@ 2@@ b@@ 7@@ a@@ 9@@ de@@ 4 \ / em@@ 01@@ 12@@ cor@@ des@@ 3@@ 30@@ 4@@ 29@@ 6@@ 40@@ x@@ 36@@ 0.@@ j@@ pg , &quot; &quot; full &quot; : &quot; http : \ / \ / c@@ b@@ s@@ news@@ 1.@@ c@@ b@@ si@@ stat@@ ic@@ .com \ / hub \ / i \ / r \ / 2015 \ / 01 \ / 13 \ / 7@@ f@@ d@@ 70@@ 6@@ 68 @-@ e@@ eff @-@ 45@@ f@@ 0 @-@ b@@ 4@@ c@@ 3 @-@ 5@@ b@@ 3@@ b@@ 2@@ b@@ 2@@ b@@ 94@@ 57 \ / thumbnail \ / 9@@ 40@@ x@@ 470 \ / 6@@ a@@ 16@@ 68@@ 85@@ f@@ 4@@ d@@ 7@@ 114@@ 6@@ f@@ 25@@ 10@@ a@@ 0@@ c@@ f@@ 7@@ ef@@ 47@@ 12 \ / em@@ 01@@ 12@@ cor@@ des@@ 3@@ 30@@ 4@@ 29@@ 6@@ 40@@ x@@ 36@@ 0.@@ j@@ pg &quot; } , &quot; show@@ Style &quot; : &quot; video @-@ logo @-@ evening @-@ news , &quot; &quot; suppress &quot; : false , &quot; season &quot; : &quot; 1 , &quot; &quot; episode &quot; : &quot; 1 , &quot; &quot; mp@@ x@@ Re@@ f@@ Id &quot; : &quot; nc@@ O@@ t _ n@@ ET@@ br@@ HY@@ TT@@ Ab@@ X@@ 1@@ DEV@@ Q@@ 5@@ TJ@@ r@@ L@@ 1@@ mr@@ c@@ M , &quot; &quot; segment &quot; : 1 , &quot; i@@ pad@@ Block &quot; : false , &quot; topic &quot; : &quot; evening @-@ news , &quot; &quot; topic _ name &quot; : &quot; CBS Even@@ ing News , &quot; &quot; topic _ parent _ slug &quot; : &quot; evening @-@ news , &quot; &quot; topic _ parent &quot; : &quot; CBS Even@@ ing News , &quot; &quot; collection &quot; : null , &quot; pid &quot; : &quot; p@@ x@@ I@@ 2@@ b@@ 1@@ R@@ NAT@@ Es &quot; } , &quot; dz@@ Wo@@ R@@ D@@ 3@@ H@@ 8@@ ROM &quot; : { &quot; id &quot; : &quot; 3@@ b@@ 48@@ 76@@ f@@ 5 @-@ 29@@ f@@ 0 @-@ 4@@ aa@@ 9 @-@ 9@@ 29@@ a @-@ 43@@ d@@ 800@@ f@@ 39@@ 1@@ f@@ 8 , &quot; &quot; medi@@ as &quot; : { &quot; desktop &quot; : { &quot; pid &quot; : &quot; dz@@ Wo@@ R@@ D@@ 3@@ H@@ 8@@ ROM , &quot; &quot; bit@@ rate &quot; : &quot; 7@@ 64@@ 000 , &quot; &quot; uri &quot; : &quot; rt@@ mp : \ / \ / c@@ p@@ 98@@ 36@@ 3.@@ ed@@ ge@@ f@@ cs.@@ net \ / on@@ demand \ / ? au@@ th = c@@ bs \ u@@ 00@@ 26@@ ai@@ f@@ p = v@@ 001 \ u@@ 00@@ 26@@ sli@@ st = media \ / 2015 \ / 01 \ / 12 \ / 38@@ 3@@ 40@@ 30@@ 7@@ 58@@ 43 \ / \ u@@ 00@@ 3@@ C@@ break \ u@@ 00@@ 3@@ E@@ media \ / 2015 \ / 01 \ / 12 \ / 38@@ 3@@ 40@@ 30@@ 7@@ 58@@ 43 \ / en _ la@@ po@@ ok _ 3@@ 30@@ 407 _ 79@@ 6.@@ mp@@ 4 &quot; } , &quot; tablet &quot; : { &quot; pid &quot; : &quot; X@@ O@@ 2@@ U@@ pi@@ P@@ f@@ 27 _ S , &quot; &quot; bit@@ rate &quot; : &quot; 7@@ 40@@ 000 , &quot; &quot; uri &quot; : &quot; http : \ / \ / down@@ lo@@ ad@@ .c@@ b@@ s@@ new@@ s.com \ / media \ / mp@@ x \ / 2015 \ / 01 \ / 12 \ / 38@@ 3@@ 40@@ 30@@ 7@@ 58@@ 43 \ / en _ la@@ po@@ ok _ 3@@ 30@@ 407 _ 74@@ 0.@@ mp@@ 4 &quot; } , &quot; mobile &quot; : { &quot; pid &quot; : &quot; _ On@@ Y@@ V@@ R@@ CL@@ W@@ g@@ DR , &quot; &quot; bit@@ rate &quot; : &quot; 24@@ 0000 , &quot; &quot; uri &quot; : &quot; http : \ / \ / down@@ lo@@ ad@@ .c@@ b@@ s@@ new@@ s.com \ / media \ / mp@@ x \ / 2015 \ / 01 \ / 12 \ / 38@@ 3@@ 40@@ 30@@ 7@@ 58@@ 43 \ / en _ la@@ po@@ ok _ 3@@ 30@@ 407 _ 24@@ 0.@@ mp@@ 4 &quot; } , &quot; i@@ os &quot; : { &quot; pid &quot; : &quot; B@@ kn@@ 9@@ D@@ 9@@ G@@ sy@@ GT@@ t , &quot; &quot; bit@@ rate &quot; : &quot; 500@@ 000 , &quot; &quot; uri &quot; : &quot; http : \ / \ / i@@ pad @-@ stream@@ ing@@ .c@@ b@@ s@@ new@@ s.com \ / media \ / mp@@ x \ / 2015 \ / 01 \ / 12 \ / 38@@ 3@@ 40@@ 30@@ 7@@ 58@@ 43 \ / en _ la@@ po@@ ok _ 3@@ 30@@ 421 _ 500 \ / en _ la@@ po@@ ok _ 3@@ 30@@ 421 _ 500@@ .@@ m@@ 3@@ u@@ 8 &quot; } } , &quot; slug &quot; : &quot; dis@@ ney@@ land @-@ meas@@ les @-@ outbreak @-@ spreads , &quot; &quot; title &quot; : &quot; Disneyland meas@@ les outbreak spreads , &quot; &quot; dek &quot; : &quot; The people sick@@ ened were all at Disneyland between December 15 @-@ 20 .

**Comment by emjotde** [comment]
This is important information about Disneyland!

**Comment by hieuhoang** [comment]
you've been in the office too long. Another gem:
Find your constitu@@ ency Aber@@ av@@ on@@ Aber@@ con@@ wy@@ Aber@@ deen North@@ Aber@@ deen South@@ Aber@@ de@@ en@@ shire West and Kin@@ car@@ din@@ e@@ Air@@ dri@@ e and Shot@@ ts@@ Alder@@ shot@@ Aldr@@ idge @-@ Brow@@ n@@ hill@@ s@@ Al@@ trin@@ ch@@ am and Sale West@@ A@@ lyn and Dee@@ side@@ Amber Val@@ ley@@ Angu@@ s@@ An@@ trim East@@ An@@ trim North@@ An@@ trim South@@ Ar@@ fon@@ Ar@@ gy@@ ll and Bu@@ te@@ Ar@@ un@@ del and South Down@@ s@@ Ash@@ field@@ Ash@@ ford@@ Ashton under Ly@@ ne@@ Ay@@ les@@ bu@@ ry@@ Ay@@ r , Car@@ rick and Cum@@ no@@ ck@@ Ay@@ r@@ shire Cen@@ tral@@ Ay@@ r@@ shire North and Arran@@ Ban@@ bu@@ ry@@ Ban@@ ff and Buchan@@ Bar@@ king@@ Bar@@ n@@ sley Cen@@ tral@@ Bar@@ n@@ sley East@@ Barrow and Fur@@ ness@@ Bas@@ il@@ don South and Thur@@ rock East@@ Bas@@ il@@ don and Bill@@ er@@ ic@@ ay@@ Bas@@ ing@@ sto@@ ke@@ B@@ asse@@ tla@@ w@@ Bath@@ Bat@@ ley and Spen@@ Bat@@ ter@@ sea@@ Be@@ acon@@ s@@ field@@ Beck@@ en@@ ham@@ Bed@@ ford@@ Bed@@ fordshire Mid@@ Bed@@ fordshire North East@@ Bed@@ fordshire South West@@ Belfast East@@ Belfast North@@ Belfast South@@ Belfast West@@ Ber@@ mon@@ dsey and Old South@@ war@@ k@@ Ber@@ wick @-@ upon @-@ Twe@@ ed@@ Ber@@ wick@@ shire , Rox@@ burgh and Sel@@ kir@@ k@@ Beth@@ nal Green and Bow@@ Bever@@ ley and Hol@@ der@@ ness@@ B@@ ex@@ hill and Battle@@ B@@ ex@@ ley@@ he@@ ath and Cra@@ y@@ ford@@ Bir@@ ken@@ head@@ Birmingham Ed@@ g@@ bast@@ on@@ Birmingham Er@@ ding@@ ton@@ Birmingham Hall Green@@ Birmingham Hod@@ ge Hill@@ Birmingham Lady@@ wood@@ Birmingham North@@ field@@ Birmingham Perry Bar@@ r@@ Birmingham Sel@@ ly Oak@@ Birmingham Y@@ ard@@ ley@@ Bishop Au@@ ck@@ land@@ Black@@ bur@@ n@@ Black@@ ley and B@@ rough@@ ton@@ Black@@ pool North and Cle@@ vele@@ ys@@ Black@@ pool South@@ Bla@@ en@@ au Gw@@ ent@@ Bla@@ y@@ don@@ B@@ ly@@ th Val@@ ley@@ Bog@@ nor Regis and Little@@ ha@@ mp@@ ton@@ Bol@@ sover@@ Bolton North East@@ Bolton South East@@ Bolton West@@ Bo@@ ot@@ le@@ Boston and Ske@@ g@@ ness@@ Bos@@ worth@@ Bour@@ ne@@ mouth East@@ Bour@@ ne@@ mouth West@@ Bra@@ ck@@ nel@@ l@@ Brad@@ ford East@@ Brad@@ ford South@@ Brad@@ ford West@@ Bra@@ in@@ tree@@ Bre@@ con and Rad@@ nor@@ sh@@ ire@@ Brent Cen@@ tral@@ Brent North@@ Brent@@ ford and Isle@@ worth@@ Brent@@ wood and On@@ gar@@ Brid@@ gen@@ d@@ Brid@@ g@@ water and Somer@@ set West@@ Bri@@ gg and Go@@ ole@@ Brighton K@@ emp@@ town@@ Brighton Pav@@ ili@@ on@@ Bristol East@@ Bristol North West@@ Bristol South@@ Bristol West@@ Broad@@ land@@ Bro@@ mley and Chis@@ le@@ hur@@ st@@ Bro@@ ms@@ gro@@ ve@@ Bro@@ x@@ bour@@ ne@@ Bro@@ x@@ to@@ we@@ Buck@@ ing@@ ham@@ Burn@@ ley@@ Bur@@ ton@@ Bury North@@ Bury South@@ Bury St Edmun@@ ds@@ Ca@@ er@@ phil@@ ly@@ Cai@@ th@@ ness , Su@@ therland and Easter Ross@@ Cal@@ der Val@@ ley@@ Cam@@ ber@@ well and Pe@@ ck@@ ham@@ Cam@@ borne and Red@@ ru@@ th@@ Cam@@ brid@@ ge@@ Cam@@ brid@@ ge@@ shire North East@@ Cam@@ brid@@ ge@@ shire North West@@ Cam@@ brid@@ ge@@ shire South@@ Cam@@ brid@@ ge@@ shire South East@@ Can@@ nock Cha@@ se@@ Canter@@ bu@@ ry@@ Car@@ diff Cen@@ tral@@ Car@@ diff North@@ Car@@ diff South and Pen@@ ar@@ th@@ Car@@ diff West@@ Car@@ li@@ sle@@ Car@@ mar@@ then East and Din@@ ef@@ wr@@ Car@@ mar@@ then West and P@@ embro@@ ke@@ shire South@@ Car@@ shal@@ ton and Wal@@ ling@@ ton@@ Castle Po@@ int@@ Cer@@ edi@@ gion@@ Char@@ n@@ wood@@ Cha@@ tham and Ay@@ les@@ ford@@ C@@ head@@ le@@ Chel@@ ms@@ ford@@ Chelsea and Ful@@ ham@@ Chel@@ ten@@ ham@@ Che@@ sham and Amer@@ sham@@ Che@@ ster@@ field@@ Chi@@ chest@@ er@@ Ch@@ ing@@ ford and Wood@@ ford Green@@ Chi@@ p@@ pen@@ ham@@ Chi@@ pping Bar@@ net@@ Chor@@ ley@@ Christ@@ chur@@ ch@@ C@@ ities of London and Westmin@@ ster@@ City of Che@@ ster@@ City of Dur@@ ham@@ Cla@@ ct@@ on@@ Cle@@ e@@ thor@@ pe@@ s@@ Cl@@ wy@@ d South@@ Cl@@ wy@@ d West@@ Co@@ at@@ bridge , Chry@@ ston and Bel@@ l@@ sh@@ ill@@ Col@@ chest@@ er@@ Col@@ ne Val@@ ley@@ Con@@ gle@@ ton@@ Cop@@ el@@ and@@ Cor@@ by@@ Corn@@ wall North@@ Corn@@ wall South East@@ Cot@@ sw@@ ol@@ d@@ Cov@@ entry North East@@ Cov@@ entry North West@@ Cov@@ entry South@@ Craw@@ ley@@ Cre@@ we and N@@ ant@@ wi@@ ch@@ Cro@@ y@@ don Cen@@ tral@@ Cro@@ y@@ don North@@ Cro@@ y@@ don South@@ Cum@@ ber@@ nau@@ ld , Kil@@ sy@@ th and Kir@@ kin@@ til@@ loch East@@ Cy@@ non Val@@ ley@@ D@@ agen@@ ham and Rain@@ ham@@ Dar@@ ling@@ ton@@ Dart@@ ford@@ Daven@@ try@@ Del@@ yn@@ D@@ enton and Red@@ dish@@ Derby North@@ Derby South@@ Der@@ by@@ shire Dal@@ es@@ Der@@ by@@ shire Mid@@ Der@@ by@@ shire North East@@ Der@@ by@@ shire South@@ Dev@@ i@@ zes@@ Devon Cen@@ tral@@ Devon East@@ Devon North@@ Devon South West@@ Devon West and Tor@@ rid@@ ge@@ De@@ w@@ s@@ bu@@ ry@@ Don Val@@ ley@@ Don@@ caster Cen@@ tral@@ Don@@ caster North@@ Dor@@ set M@@ id and Poole North@@ Dor@@ set North@@ Dor@@ set South@@ Dor@@ set West@@ D@@ over@@ Down North@@ Down South@@ Dudley North@@ Dudley South@@ Dul@@ wich and West Nor@@ wood@@ Dum@@ fries and Gal@@ lo@@ way@@ Dum@@ fri@@ es@@ shire , Cly@@ des@@ dale and Twe@@ ed@@ dale@@ Dun@@ bar@@ ton@@ shire East@@ Dun@@ bar@@ ton@@ shire West@@ Dun@@ dee East@@ Dun@@ dee West@@ Dun@@ fer@@ m@@ line and Fi@@ fe West@@ Durham North@@ Durham North West@@ D@@ wy@@ for Me@@ iri@@ on@@ ny@@ d@@ d@@ E@@ aling Central and Act@@ on@@ E@@ aling North@@ E@@ aling South@@ all@@ E@@ as@@ ing@@ ton@@ East Ham@@ East Kil@@ bride , Strath@@ aven and Les@@ ma@@ ha@@ go@@ w@@ East Lo@@ thi@@ an@@ East@@ bour@@ ne@@ East@@ le@@ igh@@ Ed@@ dis@@ bu@@ ry@@ Edinburgh East@@ Edinburgh North and Le@@ ith@@ Edinburgh South@@ Edinburgh South West@@ Edinburgh West@@ Ed@@ mon@@ ton@@ El@@ le@@ sm@@ ere Port and Nest@@ on@@ El@@ met and Roth@@ well@@ El@@ th@@ am@@ En@@ field North@@ En@@ field South@@ gate@@ E@@ pping Forest@@ Ep@@ som and E@@ well@@ Ere@@ wash@@ Eri@@ th and Tha@@ mes@@ me@@ ad@@ E@@ sher and Wal@@ ton@@ Ex@@ eter@@ Fal@@ kir@@ k@@ F@@ are@@ ham@@ F@@ aver@@ sham and Kent Mid@@ Fel@@ tham and H@@ eston@@ Fer@@ man@@ agh and South Ty@@ ro@@ ne@@ Fi@@ fe North East@@ Fil@@ ton and Bradley Sto@@ ke@@ Fin@@ ch@@ ley and Gol@@ ders Green@@ Fol@@ ke@@ stone and Hy@@ the@@ Forest of De@@ an@@ Fo@@ yle@@ F@@ yl@@ de@@ Ga@@ ins@@ bor@@ ough@@ Gar@@ ston and Hale@@ wood@@ Gate@@ she@@ ad@@ Ged@@ ling@@ G@@ ill@@ ingham and Rain@@ ham@@ Glasgow Cen@@ tral@@ Glasgow East@@ Glasgow North@@ Glasgow North East@@ Glasgow North West@@ Glasgow South@@ Glasgow South West@@ Glen@@ ro@@ the@@ s@@ Gloucest@@ er@@ Gor@@ don@@ Go@@ sport@@ Gow@@ er@@ Gran@@ tham and Stam@@ ford@@ Gra@@ ve@@ sham@@ Great Gri@@ ms@@ by@@ Great Yar@@ mouth@@ Greenwich and Wool@@ wi@@ ch@@ Guil@@ d@@ ford@@ Hack@@ ney North and Sto@@ ke New@@ ing@@ ton@@ Hack@@ ney South and Shor@@ ed@@ itch@@ Hale@@ so@@ wen and Row@@ ley Reg@@ is@@ Hali@@ fax@@ Hal@@ tem@@ price and How@@ den@@ Hal@@ ton@@ Hammer@@ smi@@ th@@ Hampshire East@@ Hampshire North East@@ Hampshire North West@@ Hamp@@ stead and Kil@@ bur@@ n@@ Har@@ bor@@ ough@@ Har@@ low@@ Har@@ rogate and K@@ nar@@ es@@ bor@@ ough@@ Har@@ row East@@ Har@@ row West@@ Har@@ tle@@ po@@ ol@@ Har@@ wich and Essex North@@ Hastings and R@@ ye@@ Hav@@ ant@@ Hayes and Har@@ ling@@ ton@@ Hazel Gro@@ ve@@ He@@ mel H@@ emp@@ stead@@ Hem@@ s@@ worth@@ H@@ end@@ on@@ Hen@@ ley@@ Here@@ ford and Here@@ fordshire South@@ Here@@ fordshire North@@ Hert@@ ford and Stor@@ t@@ ford@@ Hert@@ fordshire North East@@ Hert@@ fordshire South West@@ Hert@@ sm@@ ere@@ Hex@@ ham@@ Hey@@ wood and Middle@@ ton@@ High Pe@@ ak@@ Hitch@@ in and Har@@ pen@@ den@@ Hol@@ born and St Pan@@ cra@@ s@@ Horn@@ church and Up@@ min@@ ster@@ Horn@@ sey and Wood Green@@ Hor@@ sham@@ Hou@@ gh@@ ton and S@@ under@@ land South@@ H@@ ove@@ Hud@@ der@@ s@@ field@@ Hull East@@ Hull North@@ Hull West and Hes@@ sle@@ Hunting@@ don@@ Hy@@ n@@ d@@ bur@@ n@@ Il@@ ford North@@ Il@@ ford South@@ In@@ ver@@ c@@ ly@@ de@@ In@@ ver@@ ness , N@@ air@@ n , Bad@@ en@@ och and Strath@@ spe@@ y@@ I@@ ps@@ wi@@ ch@@ Isle of W@@ igh@@ t@@ I@@ sl@@ ington North@@ I@@ sl@@ ington South and Fin@@ s@@ bu@@ ry@@ I@@ sl@@ wy@@ n@@ Jar@@ row@@ Ke@@ igh@@ ley@@ Ken@@ il@@ worth and South@@ am@@ Kensing@@ ton@@ Ket@@ ter@@ ing@@ Kil@@ mar@@ nock and Lou@@ d@@ oun@@ King@@ ston and Sur@@ bit@@ on@@ King@@ s@@ wood@@ Kirk@@ cal@@ dy and Cow@@ den@@ be@@ ath@@ Know@@ sle@@ y@@ L@@ agan Val@@ ley@@ Lan@@ ark and Hamilton East@@ Lan@@ ca@@ shire West@@ Lan@@ caster and Fle@@ e@@ two@@ od@@ Leeds Cen@@ tral@@ Leeds East@@ Leeds North East@@ Leeds North West@@ Leeds West@@ Le@@ ic@@ ester East@@ Le@@ ic@@ ester South@@ Le@@ ic@@ ester West@@ Le@@ icest@@ er@@ shire North West@@ Le@@ icest@@ er@@ shire South@@ Leigh@@ Le@@ we@@ s@@ Lewisham De@@ pt@@ ford@@ Lewisham East@@ Lewisham West and Pen@@ ge@@ Le@@ yton and Wan@@ stead@@ Lich@@ field@@ Lincol@@ n@@ Lin@@ li@@ th@@ gow and Fal@@ kir@@ k East@@ Liverpool River@@ side@@ Liverpool Wal@@ ton@@ Liverpool W@@ aver@@ tree@@ Liverpool West Der@@ by@@ Living@@ ston@@ L@@ lan@@ elli@@ Lon@@ don@@ der@@ ry East@@ Lou@@ gh@@ bor@@ ough@@ Lou@@ th and Horn@@ cast@@ le@@ Lud@@ low@@ Lut@@ on North@@ Lut@@ on South@@ Mac@@ cle@@ s@@ field@@ Ma@@ iden@@ head@@ Ma@@ id@@ stone and The We@@ al@@ d@@ Mak@@ er@@ field@@ Mal@@ don@@ Manchester Cen@@ tral@@ Manchester Gor@@ ton@@ Manchester Wi@@ thing@@ ton@@ Mans@@ field@@ Me@@ on Val@@ ley@@ Mer@@ iden@@ Mer@@ thy@@ r Ty@@ d@@ fil and Rhy@@ m@@ ney@@ Mid@@ d@@ les@@ br@@ ough@@ Mid@@ d@@ les@@ br@@ ough South and Cleveland East@@ Mid@@ lo@@ thi@@ an@@ Milton Keynes North@@ Milton Keynes South@@ Mitch@@ am and Mor@@ den@@ M@@ ole Val@@ ley@@ Mon@@ mouth@@ Montgom@@ ery@@ sh@@ ire@@ Mor@@ ay@@ More@@ cam@@ be and Lu@@ nes@@ dale@@ Mor@@ ley and Out@@ wood@@ Mo@@ ther@@ well and Wis@@ haw@@ Na h @-@ Ei@@ lean@@ an an I@@ ar@@ Ne@@ ath@@ New Forest East@@ New Forest West@@ Newar@@ k@@ New@@ bu@@ ry@@ Newcastle upon Ty@@ ne Cen@@ tral@@ Newcastle upon Ty@@ ne East@@ Newcastle upon Ty@@ ne North@@ Newcastle @-@ under @-@ Ly@@ me@@ Newport East@@ Newport West@@ New@@ ry and Ar@@ ma@@ gh@@ Newton Abbot@@ Norfolk Mid@@ Norfolk North@@ Norfolk North West@@ Norfolk South@@ Norfolk South West@@ Norman@@ ton , Pon@@ te@@ fra@@ ct and Castle@@ ford@@ North@@ amp@@ ton North@@ North@@ amp@@ ton South@@ North@@ amp@@ ton@@ shire South@@ Nor@@ wich North@@ Nor@@ wich South@@ Nottingham East@@ Nottingham North@@ Nottingham South@@ N@@ une@@ aton@@ O@@ ch@@ il and Per@@ th@@ shire South@@ Og@@ more@@ Old B@@ ex@@ ley and Sid@@ cup@@ Old@@ ham East and Sad@@ dle@@ worth@@ Old@@ ham West and Roy@@ ton@@ Or@@ k@@ ney and She@@ t@@ land@@ Or@@ ping@@ ton@@ Oxford East@@ Oxford West and Ab@@ ing@@ don@@ Pa@@ is@@ ley and Ren@@ fre@@ w@@ shire North@@ Pa@@ is@@ ley and Ren@@ fre@@ w@@ shire South@@ P@@ end@@ le@@ Pen@@ ist@@ one and Stock@@ s@@ brid@@ ge@@ Pen@@ rith and The Bor@@ der@@ Per@@ th and Per@@ th@@ shire North@@ Peter@@ bor@@ ough@@ Plymouth Mo@@ or Vie@@ w@@ Plymouth Sutton and Dev@@ on@@ port@@ Pon@@ ty@@ pr@@ id@@ d@@ Po@@ ole@@ Pop@@ lar and Li@@ me@@ house@@ Port@@ sm@@ ou@@ th North@@ Port@@ sm@@ ou@@ th South@@ Pre@@ se@@ li P@@ embro@@ ke@@ sh@@ ire@@ Prest@@ on@@ P@@ ud@@ se@@ y@@ Put@@ ney@@ Ray@@ leigh and Wick@@ ford@@ Re@@ ading East@@ Re@@ ading West@@ Red@@ car@@ Red@@ dit@@ ch@@ Re@@ ig@@ ate@@ Ren@@ fre@@ w@@ shire East@@ Rhon@@ d@@ da@@ Ri@@ bble South ( South Ri@@ bble ) Ri@@ bble Val@@ ley@@ Richmond ( Yor@@ ks ) Richmond Park@@ Roch@@ dale@@ Roch@@ ester and Stro@@ od@@ Roch@@ ford and South@@ end East@@ Rom@@ ford@@ Rom@@ sey and South@@ amp@@ ton North@@ Ross , Skye and L@@ ochab@@ er@@ Ross@@ endale and Dar@@ wen@@ R@@ other Val@@ ley@@ Ro@@ ther@@ ham@@ Ru@@ g@@ by@@ Ru@@ is@@ lip , North@@ wood and Pin@@ ner@@ Run@@ ny@@ med@@ e and Wey@@ brid@@ ge@@ Rush@@ cli@@ ffe@@ Ru@@ ther@@ g@@ len and Hamilton West@@ Rut@@ land and Mel@@ ton@@ Saf@@ fro@@ n Wal@@ den@@ Sal@@ ford and Ec@@ cle@@ s@@ Sal@@ is@@ bu@@ ry@@ Scar@@ borough and Whit@@ by@@ Sc@@ un@@ thor@@ pe@@ Sed@@ ge@@ field@@ Sef@@ ton Cen@@ tral@@ Sel@@ by and A@@ inst@@ y@@ Seven@@ o@@ ak@@ s@@ She@@ f@@ field Bri@@ ght@@ side and Hill@@ sbor@@ ough@@ She@@ f@@ field Cen@@ tral@@ She@@ f@@ field Hal@@ lam@@ She@@ f@@ field He@@ ele@@ y@@ She@@ f@@ field South East@@ Sher@@ wood@@ Shi@@ ple@@ y@@ Sh@@ re@@ w@@ s@@ bury and At@@ cham@@ Sh@@ rop@@ shire North@@ Sit@@ ting@@ bourne and Shep@@ pe@@ y@@ Sk@@ ip@@ ton and Ri@@ pon@@ S@@ lea@@ ford and North Hy@@ ke@@ ham@@ Slou@@ gh@@ Soli@@ hul@@ l@@ Somer@@ set North@@ Somer@@ set North East@@ Somer@@ ton and Fro@@ me@@ South Holland and The Deep@@ ings@@ South Shi@@ el@@ ds@@ South@@ amp@@ ton It@@ chen@@ South@@ amp@@ ton Test@@ South@@ end West@@ South@@ port@@ Spel@@ thor@@ ne@@ St Al@@ ban@@ s@@ St Aust@@ ell and New@@ qu@@ ay@@ St Hel@@ ens North@@ St Hel@@ ens South and Whist@@ on@@ St I@@ ves@@ Sta@@ f@@ ford@@ Sta@@ f@@ fordshire Mo@@ or@@ land@@ s@@ Sta@@ f@@ fordshire South@@ St@@ aly@@ bridge and Hy@@ de@@ Steven@@ age@@ Stir@@ ling@@ Stock@@ port@@ Stock@@ ton North@@ Stock@@ ton South@@ Sto@@ ke @-@ on @-@ Trent Cen@@ tral@@ Sto@@ ke @-@ on @-@ Trent North@@ Sto@@ ke @-@ on @-@ Trent South@@ Stone@@ St@@ our@@ brid@@ ge@@ Stran@@ g@@ ford@@ Strat@@ ford @-@ on @-@ A@@ von@@ Stre@@ ath@@ am@@ Stre@@ t@@ ford and Ur@@ m@@ ston@@ S@@ trou@@ d@@ Suf@@ folk Central and I@@ ps@@ wich North@@ Suf@@ folk Co@@ ast@@ al@@ Suf@@ folk South@@ Suf@@ folk West@@ S@@ under@@ land Cen@@ tral@@ Surrey East@@ Surrey He@@ ath@@ Surrey South West@@ Sus@@ sex Mid@@ Sutton Col@@ d@@ field@@ Sutton and Che@@ am@@ Swan@@ sea East@@ Swan@@ sea West@@ S@@ win@@ don North@@ S@@ win@@ don South@@ Tam@@ worth@@ Tat@@ ton@@ Ta@@ un@@ ton De@@ ane@@ Tel@@ ford@@ Te@@ w@@ ke@@ s@@ bu@@ ry@@ Than@@ et North@@ Than@@ et South@@ The W@@ re@@ kin@@ Thir@@ sk and Mal@@ ton@@ Thorn@@ bury and Y@@ ate@@ Thur@@ rock@@ Ti@@ ver@@ ton and Hon@@ it@@ on@@ Ton@@ bridge and Mal@@ ling@@ To@@ ot@@ ing@@ Tor@@ bay@@ Tor@@ fa@@ en@@ Tot@@ nes@@ Tot@@ ten@@ ham@@ Tr@@ uro and Fal@@ mouth@@ Tun@@ bridge Wel@@ ls@@ Tw@@ ick@@ en@@ ham@@ Ty@@ ne@@ mouth@@ Ty@@ ne@@ side North@@ Tyrone West@@ Ul@@ ster Mid@@ Upper Ban@@ n@@ U@@ x@@ bridge and Ru@@ is@@ lip South@@ Vale of Cl@@ wy@@ d@@ Vale of Gla@@ mor@@ gan@@ Vau@@ x@@ hall@@ Wake@@ field@@ Walla@@ se@@ y@@ Wal@@ s@@ all North@@ Wal@@ s@@ all South@@ Wal@@ th@@ am@@ sto@@ w@@ W@@ ans@@ be@@ ck@@ W@@ anta@@ ge@@ War@@ ley@@ War@@ rington North@@ War@@ rington South@@ Warwick and Le@@ am@@ ing@@ ton@@ War@@ wick@@ shire North@@ Washington and S@@ under@@ land West@@ Wat@@ ford@@ W@@ av@@ ene@@ y@@ We@@ al@@ den@@ Weaver V@@ ale@@ Welling@@ bor@@ ough@@ Wel@@ ls@@ Wel@@ wyn Hat@@ field@@ Went@@ worth and Dear@@ ne@@ West Bro@@ m@@ wich East@@ West Bro@@ m@@ wich West@@ West Ham@@ Westmin@@ ster North@@ West@@ mor@@ land and Lon@@ s@@ dale@@ Weston @-@ Super @-@ Mar@@ e@@ Wig@@ an@@ Wil@@ t@@ shire North@@ Wil@@ t@@ shire South West@@ Wim@@ bled@@ on@@ Win@@ chest@@ er@@ Wind@@ sor@@ Wir@@ ral South@@ Wir@@ ral West@@ With@@ am@@ Wit@@ ney@@ W@@ ok@@ ing@@ W@@ ok@@ ing@@ ham@@ Wolver@@ ha@@ mpton North East@@ Wolver@@ ha@@ mpton South East@@ Wolver@@ ha@@ mpton South West@@ Wor@@ cest@@ er@@ Wor@@ cest@@ er@@ shire Mid@@ Wor@@ cest@@ er@@ shire West@@ Wor@@ king@@ ton@@ Wor@@ sley and Ec@@ cles South@@ Wor@@ thing East and S@@ hore@@ ham@@ Wor@@ thing West@@ W@@ rex@@ ham@@ Wy@@ com@@ be@@ Wy@@ re Forest@@ Wy@@ re and Preston North@@ Wy@@ then@@ sha@@ we and Sale East@@ Ye@@ ov@@ il@@ Y@@ n@@ ys Mon@@ York Cen@@ tral@@ York Ou@@ ter@@ Yorkshire East

**Comment by emjotde** [comment]
I am not convinced yet. Three more please.

**Comment by hieuhoang** [comment]
i'm gonna be booted of github for using up their bandwidth

**Comment by hieuhoang** [comment]
ok. i'm adding a -max-length arg to defend against these input, default=500. It doesn't solve the problem when u push the mini-batch size too far

lets see what happens after the optimized broadcast

**Comment by emjotde** [comment]
Is this a hard truncate?

**Comment by emjotde** [comment]
The optimization should actually solve the problem, it will reduce it by a factor of 2048. I do not think there is another matrix that has these combinatorial resizes.
